version: '3'
elasticsearch-common-env: &elasticsearch-common-env
  - ELASTICSEARCH_PLUGINS=analysis-icu,repository-gcs,discovery-gce
  - ES_JAVA_OPTS=-Xms512m -Xmx512m

elasticsearch-common-ulimits: &elasticsearch-common-ulimits
  memlock:
    soft: -1
    hard: -1

services:
  elasticsearch-master:
    image: my-custom-elasticsearch-master:7.4.2
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch-master
    # restart: on-failure
    container_name: elasticsearch-master
    ulimits:
      <<: *elasticsearch-common-ulimits
    environment:
      <<: *elasticsearch-common-env
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  elasticsearch-data1:
    depends_on:
      - elasticsearch-master
    image: my-custom-elasticsearch-data:7.4.2
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch-data
    container_name: elasticsearch-data1
    ulimits:
      <<: *elasticsearch-common-ulimits
    environment:
       <<: *elasticsearch-common-env
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic

  elasticsearch-data2:  # optional
    depends_on:
      - elasticsearch-master
    image: my-custom-elasticsearch-data:7.4.2
    container_name: elasticsearch-data2
    ulimits:
      <<: *elasticsearch-common-ulimits
    environment:
      <<: *elasticsearch-common-env
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    depends_on:
      - elasticsearch-master
    image: my-custom-kibana:7.4.2
    build:
      context: ./
      dockerfile: Dockerfile.kibana
    container_name: kibana
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch-master
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  plugin_volume:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
