version: '3'
services:
  elasticsearch-master:
    image: bitnami/elasticsearch:latest
    restart: on-failure
    container_name: elasticsearch-master
    environment:
      - node.name=elasticsearch-master
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-master
      - cluster.initial_master_nodes=elasticsearch-master
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  elasticsearch-data1:
    image: bitnami/elasticsearch:latest
    container_name: elasticsearch-data1
    environment:
      - node.name=elasticsearch-data1
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic

  elasticsearch-data2:  # optional
    image: bitnami/elasticsearch:latest
    container_name: elasticsearch-data2
    environment:
      - node.name=elasticsearch-data2
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: bitnami/kibana:latest
    container_name: kibana
    restart: on-failure
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-master:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
