version: '3'
services:
  elasticsearch-master:
    image: bitnami/elasticsearch:7.4.2
    # restart: on-failure
    container_name: elasticsearch-master
    volumes:
      - ./elasticsearch-master.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml
      - plugin_volume:/usr/share/elasticsearch/plugins
      - ./docker-entrypoint-es-plugins.sh:/docker-entrypoint-initdb.d
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
       - ELASTICSEARCH_PLUGINS=analysis-icu,analysis-ik
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  elasticsearch-data1:
    depends_on:
      - elasticsearch-master
    image: bitnami/elasticsearch:7.4.2
    container_name: elasticsearch-data1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./elasticsearch-data.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic

  elasticsearch-data2:  # optional
    depends_on:
      - elasticsearch-master
    image: bitnami/elasticsearch:7.4.2
    container_name: elasticsearch-data2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - ./elasticsearch-data.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic

  kibana:
    depends_on:
      - elasticsearch-master
    image: bitnami/kibana:7.4.2
    container_name: kibana
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch-master
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  plugin_volume:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
